Repository Aycraft/Aycraft, pull requests merged in 2019-02, with the labels that each got.

#9 Mise à jour du dossier commun : 19w05f
  data/commun/functions/connexion/ancien_joueur/detection.mcfunction
  data/commun/functions/connexion/ancien_joueur/trigger.mcfunction
  data/commun/functions/connexion/nouveau_joueur/detection.mcfunction
  data/commun/functions/connexion/nouveau_joueur/plus_nouveau.mcfunction
  data/commun/functions/connexion/nouveau_joueur/trigger.mcfunction
  data/commun/functions/global_serveur/gamerules.mcfunction
  data/commun/functions/grades/attribution.mcfunction
  data/commun/functions/grades/creation.mcfunction
  data/commun/functions/grades/protection/correction.mcfunction
  data/commun/functions/grades/protection/verification.mcfunction
  data/commun/functions/grades/refresh.mcfunction
  data/commun/functions/load.mcfunction
  data/commun/functions/outils/constantes.mcfunction
  data/commun/functions/outils/detection_mouvement/refresh.mcfunction
  data/commun/functions/outils/detection_mouvement/reset.mcfunction
  data/commun/functions/outils/detection_mouvement/yeux.mcfunction
  data/commun/functions/outils/invincibilite.mcfunction
  data/commun/functions/outils/tags/motion.mcfunction
  data/commun/functions/outils/uuid/attribution.mcfunction
  data/commun/functions/scores.mcfunction
  data/commun/functions/stats/scores.mcfunction
  data/commun/functions/tags.md
  data/commun/functions/tick.mcfunction
  data/commun/functions/triggers/entitees/detect.mcfunction
  data/commun/functions/triggers/entitees/reset.mcfunction
  data/commun/functions/triggers/items/detect.mcfunction
  data/commun/functions/triggers/items/reset.mcfunction
  data/commun/functions/triggers/joueurs/detect.mcfunction
  data/commun/functions/triggers/joueurs/reset.mcfunction
  data/commun/functions/triggers/scores.mcfunction
  data/commun/tags.md
  data/minecraft/tags/functions/load.json
  data/minecraft/tags/functions/tick.json
  data/spawn/functions/gestion_joueur/securite.mcfunction
  data/spawn/functions/tick.mcfunction
Labels: amélioration

#10 Mise à jour 19w07a
  data/commun/functions/global_serveur/gamerules.mcfunction
  data/commun/functions/grades/creation.mcfunction
  data/commun/functions/load.mcfunction
  data/commun/functions/outils/constantes.mcfunction
  data/commun/functions/scores.mcfunction
  data/minecraft/tags/functions/load.json
  data/spawn/functions/load.mcfunction
  data/spawn/functions/scores.mcfunction
Labels: amélioration

#11 Mise à jour 17w07b
  data/commun/functions/global_serveur/gamerules.mcfunction
  data/commun/functions/grades/creation.mcfunction
  data/commun/functions/load.mcfunction
  data/commun/functions/outils/constantes.mcfunction
  data/commun/functions/scores.mcfunction
  data/spawn/functions/load.mcfunction
  data/spawn/functions/scores.mcfunction
Labels: amélioration

#12 Mise à jour 19w07c
  data/commun/functions/global_serveur/gamerules.mcfunction
  data/commun/functions/grades/creation.mcfunction
  data/commun/functions/load.mcfunction
  data/commun/functions/outils/constantes.mcfunction
  data/commun/functions/scores.mcfunction
  data/commun/functions/tick.mcfunction
  data/minecraft/functions/load.mcfunction
  data/minecraft/tags/functions/load.json
  data/spawn/functions/load.mcfunction
  data/spawn/functions/scores.mcfunction
  data/zombie/functions/load.mcfunction
  data/zombie/functions/tick.mcfunction
  data/zombie/tags.md
Labels: amélioration, correction de bug

#15 Mise à jour 19w08c
  data/commande/functions/general/spawn.mcfunction
  data/commande/functions/scores.mcfunction
  data/commande/functions/tick.mcfunction
  data/destination/functions/spawn/spawn.mcfunction
  data/destination/functions/zombie/zombie.mcfunction
  data/minecraft/tags/functions/tick.json
Labels: amélioration, correction de bug

#17 Mise à jour 18w08d
  README.md
Labels: amélioration, docs

#18 Ajout du kit Blaze du Zombie
  data/commande/functions/general.mcfunction/spawn.mcfunction
  data/commun/functions/load.mcfunction
  data/commun/functions/scores.mcfunction
  data/commun/functions/tick.mcfunction
  data/commun/functions/triggers/joueurs/reset.mcfunction
  data/commun/functions/triggers/scores.mcfunction
  data/destination/functions/spawn/spawn.mcfunction
  data/destination/functions/zombie/zombie.mcfunction
  data/minecraft/functions/load.mcfunction
  data/spawn/functions/gestion_joueur/securite.mcfunction
  data/spawn/functions/load.mcfunction
  data/zombie/functions/load.mcfunction
  data/zombie/functions/mode_vagues/apparition/point_spawn.mcfunction
  data/zombie/functions/mode_vagues/attaque_speciale/blaze.mcfunction
  data/zombie/functions/mode_vagues/kit/aycoin/blaze.mcfunction
  data/zombie/functions/mode_vagues/kit/gratuit/alex.mcfunction
  data/zombie/functions/mode_vagues/kit/gratuit/steve.mcfunction
  data/zombie/functions/mode_vagues/kit/reinitialisation.mcfunction
  data/zombie/functions/mode_vagues/mobs/zombies/niveau_00.mcfunction
  data/zombie/functions/mode_vagues/mobs/zombies/niveau_01.mcfunction
  data/zombie/functions/mode_vagues/nom/detection_pv.mcfunction
  data/zombie/functions/mode_vagues/nom/perte_bouclier.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/affichage/00-19.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/affichage/20-39.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/affichage/40-59.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/affichage/60-79.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/affichage/80-99.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage/calcul.mcfunction
  data/zombie/functions/mode_vagues/nom/pourcentage_pv.mcfunction
  data/zombie/functions/scores.mcfunction
  data/zombie/functions/tick.mcfunction
  data/zombie/tags.md
Labels: amélioration, correction de bug
